### PR TITLE
[DO NOT MERGE] Optimize webpack build for 3rd party libraries

### PR DESCRIPTION
**Pull request by muenzpraeger**

### CODE REVIEW

**Comment by muenzpraeger** [comment]
Can't be merged before https://github.com/salesforce/lwc-test/issues/14 is solved.

**Comment by pozil** [comment]
@muenzpraeger is that PR still relevant?

**Comment by muenzpraeger** [comment]
It is. Waiting for LWC Jest to be updated with LWC 1.1 and [this PR](https://github.com/salesforce/lwc-test/pull/15).

**Comment by pozil** [comment]
Looks like that can be merged in the near future as those PRs are now merged and LWC Jest with LWC 1.1 is available in pre-release.

**Comment by muenzpraeger** [comment]
Seems we also need another config in Jest... @pozil

**Comment by pozil** [comment]
Issue solved that wasn't related with Jest, we were missing a Babel plugin for dynamic import.

**Comment by pozil** [comment]
Uh now that's weird, I fixed my tests locally, they pass with the Babel plugin but not in CI...

**Comment by pozil** [comment]
Ok so CI is running node v12 whereas I'm on v10.
What's our policy regarding node version? lwc-services is still v10+ right?

**Comment by muenzpraeger** [comment]
It's 10+. Also LTS is 12.

**Comment by muenzpraeger** [comment]
How did you fix them? Because it needs to be part of the jest config.

**Comment by pozil** [comment]
Look at my commit: I didn't touch Jest, I just added a Babel plugin to support dynamic imports (the test error mentions that).
This fixed the issue for Node v10 but we need to investigate v12...

**Comment by muenzpraeger** [comment]
It needs to be configured [here](https://github.com/salesforce/lwc-test/pull/15/files#diff-7e3e915de21c4e0d6385a5868d006d35L34), otherwise Jest won't apply it.

**Comment by pozil** [comment]
It turns out that the error has nothing to do with Node version. It's about how Node is configured to deal with unhandled exceptions. On local I just see a warning but on CI it kills the process.

**Comment by pozil** [comment]
The config you pointed out is not standard to Jest, that's something we did specifically with LWC tooling so it's beyond our reach in this repo.

As you pointed out this is fixed in the official `@lwc/jest-transformer` module but you're using your own fork of this repo in `lwc-services`: https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/package.json#L19

Can you go back to the official repo or update your fork then update `lwc-services`?

**Comment by muenzpraeger** [comment]
Ah - my bad. I changed that in the upcoming [2.0 release](https://github.com/muenzpraeger/create-lwc-app/blob/rw/release-2.0/packages/%40muenzpraeger/lwc-services-jest/package.json#L10). That should hopefully land soon.

**Pull request closed without merging**
