### PR TITLE
fix: added explicit CSP policies to fix book search error and other w…

### PR DESCRIPTION
**Pull request by sunqing99**
…arnings

### What does this PR do?

Set explicit CSP policies for helmet

### What issues does this PR fix or reference?

At the [recipes.lwc site](https://recipes.lwc.dev/#misc) the book search example does not work because of CSP violation

#<Insert GitHub Issue>

## The PR fulfills these requirements:

[ ] Tests for the proposed changes have been added/updated.
[ ] Code linting and formatting was performed.

### Functionality Before

<insert gif and/or summary>

### Functionality After

<insert gif and/or summary>

### CODE REVIEW

**Review by pozil — APPROVED** [review]
Works for me. Thanks for the contrib @sunqing99.

**Comment by msrivastav13** [comment]
@sunqing99 Thank you for your contributions! Would you mind signing the CLA for this commit so we can get it merged!

**Comment by sunqing99** [comment]
I did fill out a form, which I just did again (see screenshot attached).

Not sure whether that is the CLA you mentioned?

(I did the same for another unrelated PR
<https://github.com/developerforce/GIFter/pull/6> a week ago and it still
remains salesforce-cla check failing)

Qing

**Comment by pozil** [comment]
I guess that the CLA bot is not behaving correctly.
@msrivastav13 let's merge this anyway since Qing is an employee.

**Pull request merged**
